package com.example.dodojob.data.announcement.skillsorexprience2;

data class SkillDto (
    val id : Long,
    val skill : String
)

/*
create table public.skills_or_experience (
id bigint generated by default as identity not null,
id_skill bigint not null default nextval('tmp_id_seq'::regclass),
skill text null,
constraint skills_or_experience_pkey primary key (id_skill),
constraint skills_or_experience_id_fkey foreign KEY (id) references announcement (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
 */
